# Generated by Django 3.2.6 on 2021-08-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happ', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
