# Generated by Django 3.2.6 on 2021-08-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happ', '0003_auto_20210807_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='img',
            field=models.ImageField(default=1, upload_to='doctors'),
            preserve_default=False,
        ),
    ]
