# Generated by Django 3.2.5 on 2021-07-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodkartapp', '0002_auto_20210731_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
